name: Build Snap Package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Install snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install core
          sudo snap install snapcraft --classic

      - name: Build snap
        run: |
          cd snap
          snapcraft --destructive-mode

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: fwupd-snap
          path: snap/*.snap
